name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # - uses: sudo apt-get update && sudo apt-get install mercurial
    - name: clone gmp
      uses: hg clone https://gmplib.org/repo/gmp/ gmp
    - name: configure
      run: ./configure --with-newlib --without-headers --enable-initfini-array --disable-nls --disable-shared --disable-multilib --disable-decimal-float --disable-threads  --disable-libatomic --disable-libgomp --disable-libquadmath --disable-libssp --disable-libvtv --disable-libstdcxx --enable-languages=c,c++
    - name: make
      run: make
